apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /data']
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data
      containers:
      - name: my-python-app
        image: localhost:5000/my-python-app:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: my-python-app-config
        - secretRef:
            name: my-python-app-secret
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data # Ensure this matches your Django DATABASES configuration
        command: ["/bin/sh", "-c"]
        args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
